roles:
  - name: geerlingguy.pip
    version: 2.0.0
  - name: geerlingguy.docker
    version: 7.0.0
  - name: datadog.datadog
    version: 5.2.0
collections:
  - name: community.docker
    version: 3.0.0
